### ISSUE TITLE
feat: ファイル名テキスト表記について

### ISSUE THREAD

**Issue by adachi6k** [shioyadan/meno#1]
要求がうまく整理できておらずPRでもないので、Feedbackだけさせてください。

## 概要
レンダリング時、矩形領域が十分確保できた場合にのみテキスト情報が表示されますが、
下記のように、少し疎で初見で把握できる情報量が少なく感じます。
単純にフォントサイズを小さくすればよいのか、領域サイズに合わせてフォントサイズを小さくするのが良いか。

<img width="715" alt="image" src="https://github.com/user-attachments/assets/25bd8f55-0a8f-425e-b52b-a27537ac1fe4">

**Comment by shioyadan** [comment]
テストのために私の home の上層のファイルのデータだけ埋め込んでたんですが，これは小さいファイルに偏っていて，普通はあんまりこうはならないかなという気分ではあります．

テスト用に RSD を Vivado で合成した結果のファイルを送りますが，ちょっとこれで様子を見てもらえないでしょうか．
あとは，以前にそちらで別途送った変換スクリプトで変換したデータは直接読めるはずです．

[rsd-area.txt](https://github.com/user-attachments/files/17350594/rsd-area.txt)

フォントサイズや表示の有無はそのうち設定できるようにしたいです．

**Comment by adachi6k** [comment]
おっしゃる通りのようです。少し様子見るで取り下げます。
